/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.6.17 : Database - survey
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`survey` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `survey`;

/*Table structure for table `survey_response` */

DROP TABLE IF EXISTS `survey_response`;

CREATE TABLE `survey_response` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Nationality` varchar(200) DEFAULT NULL,
  `Ethnicity_Race` int(11) DEFAULT NULL,
  `Ethnicity_Race_Other` varchar(200) DEFAULT NULL,
  `Gender` int(11) DEFAULT NULL,
  `Birthyear` varchar(200) DEFAULT NULL,
  `Institution` varchar(200) DEFAULT NULL,
  `Country` varchar(200) DEFAULT NULL,
  `Modeofstudy` int(11) DEFAULT NULL,
  `Institutiontype` int(11) DEFAULT NULL,
  `Institutiontype_Other` varchar(200) DEFAULT NULL,
  `Levelofeducation` int(11) DEFAULT NULL,
  `Levelofeducation_Other` varchar(200) DEFAULT NULL,
  `Programme` int(11) DEFAULT NULL,
  `Programme_Other` varchar(200) DEFAULT NULL,
  `Language` int(11) DEFAULT NULL,
  `Language_Other` varchar(200) DEFAULT NULL,
  `Firstlanguage` int(11) DEFAULT NULL,
  `Firstlanguage_Other` varchar(200) DEFAULT NULL,
  `Plan` int(11) DEFAULT NULL,
  `Plan_Other` varchar(200) DEFAULT NULL,
  `Influence_Institution` int(11) DEFAULT '0',
  `Influence_Teachers` int(11) DEFAULT '0',
  `Influence_Jobmarket` int(11) DEFAULT '0',
  `Influence_Family` int(11) DEFAULT '0',
  `Influence_IndependentSelf` int(11) DEFAULT '0',
  `Influence_friends` int(11) DEFAULT '0',
  `Influence_Media` int(11) DEFAULT '0',
  `Influence_CareerExhibition` int(11) DEFAULT '0',
  `Influence_Other` int(11) DEFAULT '0',
  `Influence_Other_Specify` varchar(200) DEFAULT NULL,
  `Guidance_classtime` int(11) DEFAULT '0',
  `Guidance_outsideclass` int(11) DEFAULT '0',
  `Guidance_duringbreaktime` int(11) DEFAULT '0',
  `Guidance_Viaemail` int(11) DEFAULT '0',
  `Guidance_Socialmedia` int(11) DEFAULT '0',
  `Age_phone` varchar(100) DEFAULT NULL,
  `Age_mobiledata` varchar(100) DEFAULT NULL,
  `Age_Wifi` varchar(100) DEFAULT NULL,
  `Frequent_Entertainment` int(11) DEFAULT NULL,
  `Frequent_Education` int(11) DEFAULT NULL,
  `Frequent_Keepintouch` int(11) DEFAULT NULL,
  `Frequent_news` int(11) DEFAULT NULL,
  `Frequent_otherpurpose` int(11) DEFAULT NULL,
  `Socialmedia_sites_Facebook` int(11) DEFAULT '0',
  `Socialmedia_sites_Youtube` int(11) DEFAULT '0',
  `Socialmedia_sites_Instagram` int(11) DEFAULT '0',
  `Socialmedia_sites_Qzone` int(11) DEFAULT '0',
  `Socialmedia_sites_weibo` int(11) DEFAULT '0',
  `Socialmedia_sites_Twitter` int(11) DEFAULT '0',
  `Socialmedia_sites_reddit` int(11) DEFAULT '0',
  `Socialmedia_sites_Pinterest` int(11) DEFAULT '0',
  `Socialmedia_sites_Ask_fm` int(11) DEFAULT '0',
  `Socialmedia_sites_Tumblr` int(11) DEFAULT '0',
  `Socialmedia_sites_Flickr` int(11) DEFAULT '0',
  `Socialmedia_sites_Google` int(11) DEFAULT '0',
  `Socialmedia_app_Whatsapp` int(11) DEFAULT '0',
  `Socialmedia_app_Messenger` int(11) DEFAULT '0',
  `Socialmedia_app_WeChat` int(11) DEFAULT '0',
  `Socialmedia_app_Instagram` int(11) DEFAULT '0',
  `Socialmedia_app_Qzone` int(11) DEFAULT '0',
  `Socialmedia_app_Viber` int(11) DEFAULT '0',
  `Socialmedia_app_LINE` int(11) DEFAULT '0',
  `Socialmedia_app_Snapchat` int(11) DEFAULT '0',
  `Socialmedia_app_YY` int(11) DEFAULT '0',
  `Socialmediausage_rank` int(11) DEFAULT NULL,
  `studyindependent` int(11) DEFAULT NULL,
  `brainstorm` int(11) DEFAULT NULL,
  `direction` int(11) DEFAULT NULL,
  `material_digital` int(11) DEFAULT NULL,
  `memorizefact` int(11) DEFAULT NULL,
  `visualize` int(11) DEFAULT NULL,
  `shortnote` int(11) DEFAULT NULL,
  `discuss_friends` int(11) DEFAULT NULL,
  `differentsource` int(11) DEFAULT NULL,
  `writedown` int(11) DEFAULT NULL,
  `ownresponsibility` int(11) DEFAULT NULL,
  `motivation_instructor` int(11) DEFAULT NULL,
  `trust_instructor` int(11) DEFAULT NULL,
  `guidance_friends` int(11) DEFAULT NULL,
  `Q1_a` int(11) DEFAULT NULL,
  `Q1_b` int(11) DEFAULT NULL,
  `Q2_a` int(11) DEFAULT NULL,
  `Q2_b` int(11) DEFAULT NULL,
  `Q3_a` int(11) DEFAULT NULL,
  `Q3_b` int(11) DEFAULT NULL,
  `Q4_a` int(11) DEFAULT NULL,
  `Q4_b` int(11) DEFAULT NULL,
  `Q5_a` int(11) DEFAULT NULL,
  `Q5_b` int(11) DEFAULT NULL,
  `Q6_a` int(11) DEFAULT NULL,
  `Q6_b` int(11) DEFAULT NULL,
  `Q7_a` int(11) DEFAULT NULL,
  `Q7_b` int(11) DEFAULT NULL,
  `Q8_a` int(11) DEFAULT NULL,
  `Q8_b` int(11) DEFAULT NULL,
  `Q9_a` int(11) DEFAULT NULL,
  `Q9_b` int(11) DEFAULT NULL,
  `Q10_a` int(11) DEFAULT NULL,
  `Q10_b` int(11) DEFAULT NULL,
  `Q11_a` int(11) DEFAULT NULL,
  `Q11_b` int(11) DEFAULT NULL,
  `Q12_a` int(11) DEFAULT NULL,
  `Q12_b` int(11) DEFAULT NULL,
  `Q13_a` int(11) DEFAULT NULL,
  `Q13_b` int(11) DEFAULT NULL,
  `Q14_a` int(11) DEFAULT NULL,
  `Q14_b` int(11) DEFAULT NULL,
  `Q15_a` int(11) DEFAULT NULL,
  `Q15_b` int(11) DEFAULT NULL,
  `Q16_a` int(11) DEFAULT NULL,
  `Q16_b` int(11) DEFAULT NULL,
  `Q17_a` int(11) DEFAULT NULL,
  `Q17_b` int(11) DEFAULT NULL,
  `Q18_a` int(11) DEFAULT NULL,
  `Q18_b` int(11) DEFAULT NULL,
  `Q19_a` int(11) DEFAULT NULL,
  `Q19_b` int(11) DEFAULT NULL,
  `Q20_a` int(11) DEFAULT NULL,
  `Q20_b` int(11) DEFAULT NULL,
  `Q21_a` int(11) DEFAULT NULL,
  `Q21_b` int(11) DEFAULT NULL,
  `Q22_a` int(11) DEFAULT NULL,
  `Q22_b` int(11) DEFAULT NULL,
  `Q23_a` int(11) DEFAULT NULL,
  `Q23_b` int(11) DEFAULT NULL,
  `Q24_a` int(11) DEFAULT NULL,
  `Q24_b` int(11) DEFAULT NULL,
  `Q25_a` int(11) DEFAULT NULL,
  `Q25_b` int(11) DEFAULT NULL,
  `Q26_a` int(11) DEFAULT NULL,
  `Q26_b` int(11) DEFAULT NULL,
  `Q27_a` int(11) DEFAULT NULL,
  `Q27_b` int(11) DEFAULT NULL,
  `Q28_a` int(11) DEFAULT NULL,
  `Q28_b` int(11) DEFAULT NULL,
  `Q29_a` int(11) DEFAULT NULL,
  `Q29_b` int(11) DEFAULT NULL,
  `Q30_a` int(11) DEFAULT NULL,
  `Q30_b` int(11) DEFAULT NULL,
  `Q31_a` int(11) DEFAULT NULL,
  `Q31_b` int(11) DEFAULT NULL,
  `Q32_a` int(11) DEFAULT NULL,
  `Q32_b` int(11) DEFAULT NULL,
  `Q33_a` int(11) DEFAULT NULL,
  `Q33_b` int(11) DEFAULT NULL,
  `Q34_a` int(11) DEFAULT NULL,
  `Q34_b` int(11) DEFAULT NULL,
  `Q35_a` int(11) DEFAULT NULL,
  `Q35_b` int(11) DEFAULT NULL,
  `Q36_a` int(11) DEFAULT NULL,
  `Q36_b` int(11) DEFAULT NULL,
  `Q37_a` int(11) DEFAULT NULL,
  `Q37_b` int(11) DEFAULT NULL,
  `Q38_a` int(11) DEFAULT NULL,
  `Q38_b` int(11) DEFAULT NULL,
  `Q39_a` int(11) DEFAULT NULL,
  `Q39_b` int(11) DEFAULT NULL,
  `Q40_a` int(11) DEFAULT NULL,
  `Q40_b` int(11) DEFAULT NULL,
  `Q41_a` int(11) DEFAULT NULL,
  `Q41_b` int(11) DEFAULT NULL,
  `Q42_a` int(11) DEFAULT NULL,
  `Q42_b` int(11) DEFAULT NULL,
  `Q43_a` int(11) DEFAULT NULL,
  `Q43_b` int(11) DEFAULT NULL,
  `Q44_a` int(11) DEFAULT NULL,
  `Q44_b` int(11) DEFAULT NULL,
  `Created_Date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
